auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  #gcr.io/cadvisor/cadvisor:v0.39.3: registry.cn-hangzhou.aliyuncs.com/liy36/cadvisor:v0.39.3
  #quay.io/prometheus/alertmanager:v0.24.0: registry.cn-hangzhou.aliyuncs.com/liy36/alertmanager:v0.24.0                    
  #quay.io/prometheus/blackbox-exporter:v0.20.0: registry.cn-hangzhou.aliyuncs.com/liy36/blackbox-exporter:v0.20.0                    
  #jimmidyson/configmap-reload:v0.5.0: registry.cn-hangzhou.aliyuncs.com/liy36/configmap-reload:v0.5.0                    
  #quay.io/brancz/kube-rbac-proxy:v0.12.0: registry.cn-hangzhou.aliyuncs.com/liy36/kube-rbac-proxy:v0.12.0                    
  #grafana/grafana:8.4.5: registry.cn-hangzhou.aliyuncs.com/liy36/grafana:8.4.5                    
  #k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.4.2: registry.cn-hangzhou.aliyuncs.com/liy36/kube-state-metrics:v2.4.2                    
  #quay.io/brancz/kube-rbac-proxy:v0.12.0: registry.cn-hangzhou.aliyuncs.com/liy36/kube-rbac-proxy:v0.12.0                    
  #quay.io/prometheus-operator/prometheus-config-reloader:v0.55.1: registry.cn-hangzhou.aliyuncs.com/liy36/kube-rbac-proxy:v0.12.0                    
  #quay.io/prometheus/node-exporter:v1.3.1: registry.cn-hangzhou.aliyuncs.com/liy36/node-exporter:v1.3.1                    
  #quay.io/brancz/kube-rbac-proxy:v0.12.0: registry.cn-hangzhou.aliyuncs.com/liy36/kube-rbac-proxy:v0.12.0                    
  #quay.io/prometheus/prometheus:v2.34.0: registry.cn-hangzhou.aliyuncs.com/liy36/prometheus:v2.34.0                    
  #k8s.gcr.io/prometheus-adapter/prometheus-adapter:v0.9.1: registry.cn-hangzhou.aliyuncs.com/liy36/prometheus-adapter:v0.9.1                    
  #quay.io/prometheus-operator/prometheus-operator:v0.55.1: registry.cn-hangzhou.aliyuncs.com/liy36/prometheus-operator:v0.55.1                 
  #registry.hub.docker.com/prom/prometheus:v2.34.0: registry.cn-hangzhou.aliyuncs.com/liy36/prometheus:2.34.0
  #nginx:1.20: registry.cn-hangzhou.aliyuncs.com/liy36/nginx:1.20-official
  #golang:1.16.14: registry.cn-hangzhou.aliyuncs.com/liy36/golang:1.16.14
  #golang:1.16.15: registry.cn-hangzhou.aliyuncs.com/liy36/golang:1.16.15-official
  #ghcr.io/banzaicloud/logging-operator: liy36/banzaicloud-logging-operator
  #k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: liy36/nfs-subdir-external-provisioner
  #k8s.gcr.io/kube-apiserver: liy36/kube-apiserver
  #k8s.gcr.io/kube-controller-manager: liy36/kube-controller-manager
  #k8s.gcr.io/kube-scheduler: liy36/kube-scheduler
  #k8s.gcr.io/kube-proxy: liy36/kube-proxy
  #k8s.gcr.io/pause: liy36/pause
  #k8s.gcr.io/etcd: liy36/etcd
  #k8s.gcr.io/coredns: liy36/coredns
  #k8s.gcr.io/ingress-nginx/controller: liy36/ingress-nginx-controller
  #k8s.gcr.io/ingress-nginx/kube-webhook-certgen: liy36/ingress-nginx-kube-webhook-certgen
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.35.0: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-controller:v0.35.0
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.35.0: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-webhook:v0.35.0
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.35.0: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-kubeconfigwriter:v0.35.0
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.35.0: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-git-init:v0.35.0
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.35.0: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-entrypoint:v0.35.0
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.35.0: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-nop:v0.35.0
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.35.0: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-imagedigestexporter:v0.35.0
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.35.0: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-pullrequest-init:v0.35.0
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.35.0: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-workingdirinit:v0.35.0
  #gcr.io/google.com/cloudsdktool/cloud-sdk: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-cloud-sdk:latest
  ghcr.io/distroless/busybox: registry.cn-hangzhou.aliyuncs.com/liy36/tekton-busybox
