auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  # K8s images
  k8s.gcr.io/kube-apiserver: registry.cn-hangzhou.aliyuncs.com/k8sync/kube-apiserver
  k8s.gcr.io/kube-controller-manager: registry.cn-hangzhou.aliyuncs.com/k8sync/kube-controller-manager
  k8s.gcr.io/kube-scheduler: registry.cn-hangzhou.aliyuncs.com/k8sync/kube-scheduler
  k8s.gcr.io/kube-proxy: registry.cn-hangzhou.aliyuncs.com/k8sync/kube-proxy
  k8s.gcr.io/pause: registry.cn-hangzhou.aliyuncs.com/k8sync/pause
  k8s.gcr.io/etcd: registry.cn-hangzhou.aliyuncs.com/k8sync/etcd
  k8s.gcr.io/coredns: registry.cn-hangzhou.aliyuncs.com/k8sync/coredns

  

  # nfs storageclass
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: registry.cn-hangzhou.aliyuncs.com/k8sync/nfs-subdir-external-provisioner

  # nginx ingress
  k8s.gcr.io/ingress-nginx/controller: registry.cn-hangzhou.aliyuncs.com/k8sync/ingress-nginx-controller
  k8s.gcr.io/ingress-nginx/kube-webhook-certgen: registry.cn-hangzhou.aliyuncs.com/k8sync/ingress-nginx-kube-webhook-certgen

  # tekton 
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-pipeline-controller
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-pipeline-webhook
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-pipeline-kubeconfigwriter
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-pipeline-git-init
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-pipeline-entrypoint
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-pipeline-nop
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-pipeline-imagedigestexporter
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-pipeline-pullrequest-init
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-pipeline-workingdirinit
  ghcr.io/distroless/busybox: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-distroless-busybox
  #gcr.io/google.com/cloudsdktool/cloud-sdk: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-google-cloud-sdk
  #mcr.microsoft.com/powershell: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-powershell

  # tekton-dashboard
  gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-dashboard-dashboard
  
  # tekton-trigger
  gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-trigger-interceptors
  gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-trigger-controller
  gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-trigger-eventlistenersink
  gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook: registry.cn-hangzhou.aliyuncs.com/k8sync/tekton-trigger-webhook


  ### lsync 
  # Container monitors
  gcr.io/cadvisor/cadvisor: registry.cn-hangzhou.aliyuncs.com/lsync/cadvisor

  # Golang images
  golang: registry.cn-hangzhou.aliyuncs.com/lsync/golang
